###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{"name":"Felipe Sapogal",
"age":"42",
"email":"felipe@gmail.com"}

###

GET  http://localhost:9000/api/users HTTP/1.1
###

GET  http://localhost:9000/api/users/62ed37e734cb30d48db11963
###
PUT  http://localhost:9000/api/users/62ed37e734cb30d48db11963 HTTP/1.1
Content-Type: application/json

{"name":"Usuario Pruebas ",
"age":"21",
"email":"pruebas@gmail.com"}

###
DELETE http://localhost:9000/api/users/62eae570764202402e25ae70 HTTP/1.1
